import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { 
  BarChart, Bar, PieChart, Pie, Cell, 
  XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer,
  AreaChart, Area
} from 'recharts';
import Employee from './Employee';
import Supplier from './Supplier';
import Utensils from './Utensils';
import Ingredients from './Ingredients';
import Flavors from './Flavors';
import './Dashboard.css';

const Dashboard = () => {
  const [user, setUser] = useState(null);
  const [inventoryData, setInventoryData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [activeSection, setActiveSection] = useState('dashboard');
  const [currentTime, setCurrentTime] = useState(new Date());
  const [refreshInterval, setRefreshInterval] = useState(30000);
  const [generatingReport, setGeneratingReport] = useState(false);
  const navigate = useNavigate();

  // Update time every second
  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  // Fetch dashboard data with auto-refresh
  const fetchDashboardData = async () => {
    try {
      const token = localStorage.getItem('token');
      if (!token) {
        navigate('/login');
        return;
      }

      const res = await axios.get('http://localhost:5000/dashboard', {
        headers: {
          Authorization: `Bearer ${token}`
        }
      });
      
      setInventoryData(res.data.inventory_data);
    } catch (err) {
      console.error('Error fetching dashboard data:', err);
      if (err.response?.status === 401) {
        handleLogout();
      }
    } finally {
      setLoading(false);
    }
  };

  // Initial data fetch and setup auto-refresh
  useEffect(() => {
    const token = localStorage.getItem('token');
    const userData = JSON.parse(localStorage.getItem('user'));
    
    if (!token) {
      navigate('/login');
      return;
    }
    
    setUser(userData);
    fetchDashboardData();

    const intervalId = setInterval(fetchDashboardData, refreshInterval);
    return () => clearInterval(intervalId);
  }, [navigate, refreshInterval]);

  // Manual refresh function
  const handleRefresh = () => {
    setLoading(true);
    fetchDashboardData();
  };

  // Logout function - redirects to landing page
  const handleLogout = () => {
    // Clear all authentication data
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    localStorage.removeItem('rememberMe');
    sessionStorage.clear();
    
    // Redirect to landing page
    navigate('/');
  };

  // Generate PDF Report with Charts and Enhanced Design
  const generatePDFReport = async () => {
    try {
      setGeneratingReport(true);
      
      // Dynamically import jsPDF and html2canvas
      const { jsPDF } = await import('jspdf');
      const html2canvas = await import('html2canvas');
      
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      let yPosition = 20; // Starting Y position

      // Cover Page with Enhanced Design
      // Header with gradient-like effect
      pdf.setFillColor(212, 77, 92); // Moonberry red
      pdf.rect(0, 0, 210, 50, 'F');
      
      // Add decorative elements
      pdf.setFillColor(255, 255, 255, 30);
      pdf.circle(180, 15, 8, 'F');
      pdf.circle(160, 35, 12, 'F');
      pdf.circle(30, 25, 6, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(28);
      pdf.setFont('helvetica', 'bold');
      pdf.text('MOONBERRY CAFE', 105, 25, { align: 'center' });
      pdf.setFontSize(18);
      pdf.text('INVENTORY MANAGEMENT REPORT', 105, 35, { align: 'center' });

      // Report details with better styling
      pdf.setTextColor(60, 60, 60);
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      
      yPosition = 70;
      
      // User info box
      pdf.setFillColor(245, 245, 245);
      pdf.roundedRect(20, yPosition, 170, 30, 3, 3, 'F');
      pdf.setTextColor(212, 77, 92);
      pdf.setFont('helvetica', 'bold');
      pdf.text('REPORT DETAILS', 25, yPosition + 8);
      
      pdf.setTextColor(80, 80, 80);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Generated by: ${user?.username || 'System User'}`, 25, yPosition + 16);
      pdf.text(`Position: ${user?.role || 'User'}`, 25, yPosition + 22);
      pdf.text(`Date: ${new Date().toLocaleDateString()}`, 110, yPosition + 16);
      pdf.text(`Time: ${new Date().toLocaleTimeString()}`, 110, yPosition + 22);

      // Executive Summary with improved design
      yPosition += 45;
      pdf.setFillColor(74, 205, 196, 10); // Light teal background
      pdf.roundedRect(20, yPosition, 170, 60, 3, 3, 'F');
      
      pdf.setTextColor(212, 77, 92);
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('EXECUTIVE SUMMARY', 25, yPosition + 12);
      
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      yPosition += 20;
      
      if (inventoryData) {
        const summaryData = [
          { label: 'Total Inventory Items', value: inventoryData.total_items || 0, color: [74, 205, 196] },
          { label: 'Low Stock Items', value: inventoryData.low_stock || 0, color: [255, 159, 28] },
          { label: 'Out of Stock Items', value: inventoryData.out_of_stock || 0, color: [255, 107, 107] },
          { label: 'Total Employees', value: inventoryData.total_employees || 0, color: [163, 88, 223] }
        ];
        
        summaryData.forEach((item, index) => {
          const xPos = 25 + (index % 2) * 85;
          const yPos = yPosition + Math.floor(index / 2) * 15;
          
          // Colored dot
          pdf.setFillColor(...item.color);
          pdf.circle(xPos, yPos - 2, 2, 'F');
          
          pdf.setTextColor(60, 60, 60);
          pdf.text(`${item.label}:`, xPos + 5, yPos);
          pdf.setFont('helvetica', 'bold');
          pdf.text(item.value.toString(), xPos + 45, yPos);
          pdf.setFont('helvetica', 'normal');
        });
      }

      // Report description
      yPosition += 45;
      pdf.setTextColor(212, 77, 92);
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('REPORT OVERVIEW', 20, yPosition);
      
      pdf.setTextColor(80, 80, 80);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      yPosition += 8;
      
      const description = [
        'This comprehensive report provides detailed statistics and analytics for Moonberry Cafe',
        'inventory management. It includes real-time data covering stock levels across all categories,',
        'employee distribution, and recent inventory activity. The metrics presented offer valuable',
        'insights for inventory optimization and business decision-making.'
      ];
      
      description.forEach((line, index) => {
        pdf.text(line, 20, yPosition + (index * 5));
      });

      // Add a new page for charts and detailed data
      pdf.addPage();

      // Function to capture chart as image
      const captureChartAsImage = async (chartContainerSelector, chartName) => {
        try {
          const chartElement = document.querySelector(chartContainerSelector);
          if (chartElement) {
            const canvas = await html2canvas.default(chartElement, {
              scale: 2,
              useCORS: true,
              logging: false,
              backgroundColor: '#ffffff'
            });
            return canvas.toDataURL('image/png');
          }
        } catch (error) {
          console.error(`Error capturing ${chartName}:`, error);
        }
        return null;
      };

      // Capture all charts
      const chartsToCapture = [
        { selector: '.chart-container:first-child .recharts-wrapper', name: 'Items by Category' },
        { selector: '.chart-container:nth-child(2) .recharts-wrapper', name: 'Category Distribution' },
        { selector: '.charts-section:nth-child(3) .chart-container:first-child .recharts-wrapper', name: 'Milktea Flavors' },
        { selector: '.charts-section:nth-child(3) .chart-container:nth-child(2) .recharts-wrapper', name: 'Flavors Stock Levels' },
        { selector: '.charts-section:nth-child(4) .chart-container:first-child .recharts-wrapper', name: 'Employee Distribution' },
        { selector: '.charts-section:nth-child(4) .chart-container:nth-child(2) .recharts-wrapper', name: 'Stock Level Distribution' }
      ];

      const chartImages = [];
      for (const chart of chartsToCapture) {
        const imageData = await captureChartAsImage(chart.selector, chart.name);
        if (imageData) {
          chartImages.push({ data: imageData, name: chart.name });
        }
      }

      // Page 2: Charts
      yPosition = 20;
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(212, 77, 92);
      pdf.text('VISUAL ANALYTICS & CHARTS', 20, yPosition);

      // Add charts to PDF
      let chartYPosition = 30;
      for (let i = 0; i < chartImages.length; i += 2) {
        if (chartYPosition > 200) {
          pdf.addPage();
          chartYPosition = 20;
        }

        // First chart in row
        if (chartImages[i]) {
          pdf.setFontSize(10);
          pdf.setTextColor(80, 80, 80);
          pdf.text(chartImages[i].name, 25, chartYPosition);
          
          try {
            pdf.addImage(chartImages[i].data, 'PNG', 20, chartYPosition + 5, 80, 50);
          } catch (error) {
            console.error('Error adding chart image:', error);
          }
        }

        // Second chart in row
        if (chartImages[i + 1]) {
          pdf.setFontSize(10);
          pdf.setTextColor(80, 80, 80);
          pdf.text(chartImages[i + 1].name, 110, chartYPosition);
          
          try {
            pdf.addImage(chartImages[i + 1].data, 'PNG', 105, chartYPosition + 5, 80, 50);
          } catch (error) {
            console.error('Error adding chart image:', error);
          }
        }

        chartYPosition += 70;
      }

      // Add a new page for detailed statistics
      pdf.addPage();

      // Page 3: Detailed Statistics
      yPosition = 20;
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(212, 77, 92);
      pdf.text('DETAILED INVENTORY STATISTICS', 20, yPosition);

      // Category Statistics with table-like format
      yPosition += 15;
      pdf.setFontSize(14);
      pdf.text('CATEGORY DISTRIBUTION', 20, yPosition);
      
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      yPosition += 10;

      // Table header
      pdf.setFillColor(240, 240, 240);
      pdf.rect(20, yPosition, 170, 8, 'F');
      pdf.setTextColor(212, 77, 92);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Category', 25, yPosition + 6);
      pdf.text('Item Count', 150, yPosition + 6, { align: 'right' });
      
      yPosition += 12;

      if (inventoryData?.category_stats) {
        pdf.setTextColor(80, 80, 80);
        pdf.setFont('helvetica', 'normal');
        
        inventoryData.category_stats.forEach((category, index) => {
          if (yPosition > 270) {
            pdf.addPage();
            yPosition = 20;
            // Add header again on new page
            pdf.setFillColor(240, 240, 240);
            pdf.rect(20, yPosition, 170, 8, 'F');
            pdf.setTextColor(212, 77, 92);
            pdf.setFont('helvetica', 'bold');
            pdf.text('Category', 25, yPosition + 6);
            pdf.text('Item Count', 150, yPosition + 6, { align: 'right' });
            yPosition += 12;
          }
          
          // Alternate row colors
          if (index % 2 === 0) {
            pdf.setFillColor(250, 250, 250);
            pdf.rect(20, yPosition - 4, 170, 8, 'F');
          }
          
          const categoryName = category._id?.replace(/_/g, ' ') || 'Unknown';
          pdf.text(categoryName, 25, yPosition);
          pdf.text((category.count || 0).toString(), 150, yPosition, { align: 'right' });
          yPosition += 8;
        });
      }

      // Employee Distribution
      yPosition += 15;
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(212, 77, 92);
      pdf.text('EMPLOYEE DISTRIBUTION', 20, yPosition);
      
      pdf.setFontSize(9);
      yPosition += 10;

      // Table header
      pdf.setFillColor(240, 240, 240);
      pdf.rect(20, yPosition, 170, 8, 'F');
      pdf.setTextColor(212, 77, 92);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Position', 25, yPosition + 6);
      pdf.text('Employee Count', 150, yPosition + 6, { align: 'right' });
      
      yPosition += 12;

      if (inventoryData?.employee_stats) {
        pdf.setTextColor(80, 80, 80);
        pdf.setFont('helvetica', 'normal');
        
        inventoryData.employee_stats.forEach((employee, index) => {
          if (yPosition > 270) {
            pdf.addPage();
            yPosition = 20;
          }
          
          if (index % 2 === 0) {
            pdf.setFillColor(250, 250, 250);
            pdf.rect(20, yPosition - 4, 170, 8, 'F');
          }
          
          const position = employee._id?.replace(/_/g, ' ') || 'Unknown';
          pdf.text(position, 25, yPosition);
          pdf.text((employee.count || 0).toString(), 150, yPosition, { align: 'right' });
          yPosition += 8;
        });
      }

      // Recent Activity
      yPosition += 15;
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(212, 77, 92);
      pdf.text('RECENT ACTIVITY', 20, yPosition);
      
      pdf.setFontSize(9);
      pdf.setFont('helvetica', 'normal');
      yPosition += 10;

      if (inventoryData?.recent_activity && inventoryData.recent_activity.length > 0) {
        inventoryData.recent_activity.forEach((activity, index) => {
          if (yPosition > 270) {
            pdf.addPage();
            yPosition = 20;
          }
          
          // Color code based on action type
          let color = [80, 80, 80];
          if (activity.action === 'ADDED') color = [76, 175, 80];
          if (activity.action === 'UPDATED') color = [33, 150, 243];
          if (activity.action === 'DELETED') color = [244, 67, 54];
          
          pdf.setTextColor(...color);
          pdf.text(`• ${activity.action}:`, 25, yPosition);
          
          pdf.setTextColor(80, 80, 80);
          pdf.text(`${activity.item} - ${activity.quantity} items`, 45, yPosition);
          yPosition += 6;
        });
      } else {
        pdf.setTextColor(150, 150, 150);
        pdf.text('• No recent activity', 25, yPosition);
      }

      // Footer on all pages
      const totalPages = pdf.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        
        // Page footer
        pdf.setFontSize(8);
        pdf.setTextColor(150, 150, 150);
        pdf.text(`Generated by: ${user?.username || 'System User'} - ${user?.role || 'User'}`, 20, 290);
        pdf.text('Confidential - For Internal Use Only', 105, 290, { align: 'center' });
        pdf.text(`Page ${i} of ${totalPages}`, 190, 290, { align: 'right' });
        
        // Add moonberry logo in footer
        pdf.setFontSize(10);
        pdf.setTextColor(212, 77, 92);
        pdf.text('MOONBERRY CAFE', 105, 285, { align: 'center' });
      }

      // Save the PDF
      const fileName = `Moonberry-Inventory-Report-${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);
      
      alert('PDF report generated successfully with charts!');
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating report. Please try again.');
    } finally {
      setGeneratingReport(false);
    }
  };

  const COLORS = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFE66D', '#FF9F1C', '#A358DF', '#96CEB4', '#FFEAA7'];

  // Convert MongoDB data to chart formats
  const getChartData = () => {
    if (!inventoryData) return {};

    const stockLevelData = inventoryData.category_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      stock: item.count || 0
    })) || [];

    const categoryData = inventoryData.category_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      value: item.count || 0
    })) || [];

    const employeeData = inventoryData.employee_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      count: item.count || 0
    })) || [];

    const stockDistributionData = inventoryData.stock_stats?.map(item => ({
      name: item._id || 'Unknown',
      count: item.count || 0
    })) || [];

    const utensilData = inventoryData.utensil_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      count: item.count || 0
    })) || [];

    const ingredientData = inventoryData.ingredient_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      count: item.count || 0
    })) || [];

    const flavorData = inventoryData.flavor_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      count: item.count || 0
    })) || [];

    const milkteaFlavorsData = inventoryData.flavor_stats?.map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      stock: item.count || 0,
    })) || inventoryData.category_stats?.filter(item => 
      item._id?.includes('FLAVOR') || item._id?.includes('COFFEE') || item._id?.includes('FRUIT') ||
      item._id?.includes('CLASSIC') || item._id?.includes('SPECIALTY') || item._id?.includes('SEASONAL')
    ).map(item => ({
      name: item._id?.replace(/_/g, ' ') || 'Unknown',
      stock: item.count || 0,
    })) || [];

    return {
      stockLevelData,
      categoryData,
      employeeData,
      utensilData,
      ingredientData,
      flavorData,
      stockDistributionData,
      milkteaFlavorsData
    };
  };

  const chartData = getChartData();

  // Custom label renderer for pie chart
  const renderCustomizedLabel = ({ cx, cy, midAngle, innerRadius, outerRadius, percent, name }) => {
    const RADIAN = Math.PI / 180;
    const radius = innerRadius + (outerRadius - innerRadius) * 0.5;
    const x = cx + radius * Math.cos(-midAngle * RADIAN);
    const y = cy + radius * Math.sin(-midAngle * RADIAN);

    return (
      <text 
        x={x} 
        y={y} 
        fill="white" 
        textAnchor={x > cx ? 'start' : 'end'} 
        dominantBaseline="central"
        fontSize={12}
        fontWeight="bold"
      >
        {`${(percent * 100).toFixed(0)}%`}
      </text>
    );
  };

  // Render content based on active section
  const renderContent = () => {
    switch (activeSection) {
      case 'employees':
        return <Employee />;
      case 'suppliers':
        return <Supplier />;
      case 'utensils':
        return <Utensils />;
      case 'ingredients':
        return <Ingredients />;
      case 'flavors':
        return <Flavors />;
      case 'dashboard':
      default:
        return renderDashboardContent();
    }
  };

  const renderDashboardContent = () => (
    <>
      <div className="dashboard-header-controls">
        <h2>Inventory Overview</h2>
        <div className="refresh-controls">
          <button className="refresh-btn" onClick={handleRefresh} disabled={loading}>
            🔄 {loading ? 'Refreshing...' : 'Refresh Data'}
          </button>
          <span className="last-updated">
            Last updated: {currentTime.toLocaleTimeString()}
          </span>
        </div>
      </div>
      
      {inventoryData && (
        <>
          <div className="stats-cards">
            <div className="stat-card">
              <h3>Total Items</h3>
              <p className="stat-number">{inventoryData.total_items || 0}</p>
              <span className="stat-label">All inventory items</span>
            </div>
            <div className="stat-card">
              <h3>Low Stock</h3>
              <p className="stat-number warning">{inventoryData.low_stock || 0}</p>
              <span className="stat-label">Need restocking</span>
            </div>
            <div className="stat-card">
              <h3>Out of Stock</h3>
              <p className="stat-number danger">{inventoryData.out_of_stock || 0}</p>
              <span className="stat-label">Urgent attention</span>
            </div>
            <div className="stat-card">
              <h3>Employees</h3>
              <p className="stat-number success">{inventoryData.total_employees || 0}</p>
              <span className="stat-label">Total staff</span>
            </div>
          </div>
          
          {/* Charts Section */}
          <div className="charts-section">
            <div className="chart-container">
              <h3>Items by Category</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={chartData.stockLevelData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="name" 
                    angle={-45} 
                    textAnchor="end" 
                    height={80}
                    interval={0}
                  />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} items`, 'Count']}
                    labelFormatter={(label) => `Category: ${label}`}
                  />
                  <Legend />
                  <Bar 
                    dataKey="stock" 
                    fill="#FF6B6B" 
                    name="Number of Items"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
            
            <div className="chart-container">
              <h3>Category Distribution</h3>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={chartData.categoryData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={renderCustomizedLabel}
                    outerRadius={100}
                    fill="#8884d8"
                    dataKey="value"
                    nameKey="name"
                  >
                    {chartData.categoryData.map((entry, index) => (
                      <Cell 
                        key={`cell-${index}`} 
                        fill={COLORS[index % COLORS.length]} 
                      />
                    ))}
                  </Pie>
                  <Tooltip 
                    formatter={(value, name, props) => [
                      `${value} items`, 
                      props.payload.name
                    ]}
                  />
                  <Legend 
                    formatter={(value, entry, index) => 
                      chartData.categoryData[index]?.name || value
                    }
                  />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Milktea Flavors Section */}
          <div className="charts-section">
            <div className="chart-container">
              <h3>Milktea Flavors Stock</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={chartData.milkteaFlavorsData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="name" 
                    angle={-45} 
                    textAnchor="end" 
                    height={80}
                    interval={0}
                  />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} flavors`, 'Stock Level']}
                  />
                  <Legend />
                  <Bar 
                    dataKey="stock" 
                    fill="#A358DF" 
                    name="Number of Flavors"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
            
            <div className="chart-container">
              <h3>Flavors Stock Levels</h3>
              <ResponsiveContainer width="100%" height={300}>
                <AreaChart data={chartData.milkteaFlavorsData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="name" 
                    angle={-45} 
                    textAnchor="end" 
                    height={80}
                    interval={0}
                  />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} items`, 'Stock Level']}
                  />
                  <Legend />
                  <Area 
                    type="monotone" 
                    dataKey="stock" 
                    fill="#FF9F1C" 
                    stroke="#FF9F1C"
                    name="Stock Level"
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>
          
          <div className="charts-section">
            <div className="chart-container">
              <h3>Employee Distribution</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={chartData.employeeData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} employees`, 'Count']}
                  />
                  <Bar 
                    dataKey="count" 
                    fill="#4ECDC4" 
                    name="Number of Employees"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
            
            <div className="chart-container">
              <h3>Stock Level Distribution</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={chartData.stockDistributionData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} items`, 'Count']}
                  />
                  <Bar 
                    dataKey="count" 
                    fill="#A358DF" 
                    name="Number of Items"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="charts-section">
            <div className="chart-container">
              <h3>Utensils & Equipment</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={chartData.utensilData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="name" 
                    angle={-45} 
                    textAnchor="end" 
                    height={80}
                    interval={0}
                  />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} utensils`, 'Count']}
                  />
                  <Bar 
                    dataKey="count" 
                    fill="#FF9F1C" 
                    name="Number of Utensils"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
            
            <div className="chart-container">
              <h3>Ingredients Stock</h3>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={chartData.ingredientData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis 
                    dataKey="name" 
                    angle={-45} 
                    textAnchor="end" 
                    height={80}
                    interval={0}
                  />
                  <YAxis />
                  <Tooltip 
                    formatter={(value) => [`${value} items`, 'Count']}
                  />
                  <Bar 
                    dataKey="count" 
                    fill="#96CEB4" 
                    name="Number of Items"
                    radius={[4, 4, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="charts-section">
            <div className="chart-container full-width">
              <h3>Recent Activity</h3>
              <div className="recent-activity">
                {inventoryData.recent_activity?.length > 0 ? (
                  inventoryData.recent_activity.map((activity, index) => (
                    <div key={index} className="activity-item">
                      <span className={`activity-badge activity-${activity.action.toLowerCase()}`}>
                        {activity.action}
                      </span>
                      <span className="activity-details">
                        {activity.item} - {activity.quantity} items
                      </span>
                      <span className="activity-time">Just now</span>
                    </div>
                  ))
                ) : (
                  <div className="no-activity">
                    <p>No recent activity</p>
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="charts-section">
            <div className="chart-container full-width">
              <h3>Quick Actions</h3>
              <div className="quick-actions">
                <button className="action-btn" onClick={() => setActiveSection('suppliers')}>
                  🚚 Manage Suppliers
                </button>
                <button className="action-btn" onClick={() => setActiveSection('employees')}>
                  👥 Manage Employees
                </button>
                <button className="action-btn" onClick={() => setActiveSection('utensils')}>
                  🔪 Manage Utensils
                </button>
                <button className="action-btn" onClick={() => setActiveSection('ingredients')}>
                  🍓 Manage Ingredients
                </button>
                <button className="action-btn" onClick={() => setActiveSection('flavors')}>
                  🧋 Manage Flavors
                </button>
                <button 
                  className="action-btn" 
                  onClick={generatePDFReport}
                  disabled={generatingReport}
                >
                  {generatingReport ? '⏳ Generating Report...' : '📋 Generate PDF Report'}
                </button>
              </div>
            </div>
          </div>
        </>
      )}
    </>
  );

  if (loading && !inventoryData) {
    return <div className="dashboard-loading">Loading dashboard data...</div>;
  }

  return (
    <div className="dashboard-container">
      {/* Sidebar */}
      <div className="sidebar">
        <div className="sidebar-header">
          <h2 className="moonberry-logo">MOON<span className="logo-o">🍓</span>BERRY</h2>
          <p className="sidebar-subtitle">Cafe Inventory Management</p>
        </div>
        
        <nav className="sidebar-nav">
          <ul>
            <li className={activeSection === 'dashboard' ? 'active' : ''}>
              <span onClick={() => setActiveSection('dashboard')}>📊 Dashboard</span>
            </li>
            <li className={activeSection === 'flavors' ? 'active' : ''}>
              <span onClick={() => setActiveSection('flavors')}>🧋 Milk Tea Flavors</span>
            </li>
            <li className={activeSection === 'ingredients' ? 'active' : ''}>
              <span onClick={() => setActiveSection('ingredients')}>🍓 Ingredients</span>
            </li>
            <li className={activeSection === 'utensils' ? 'active' : ''}>
              <span onClick={() => setActiveSection('utensils')}>🔪 Utensils & Equipment</span>
            </li>
            <li className={activeSection === 'employees' ? 'active' : ''}>
              <span onClick={() => setActiveSection('employees')}>👥 Employees</span>
            </li>
            <li className={activeSection === 'suppliers' ? 'active' : ''}>
              <span onClick={() => setActiveSection('suppliers')}>🚚 Suppliers</span>
            </li>
          </ul>
        </nav>
        
        <div className="sidebar-footer">
          <div className="user-welcome">
            <span className="welcome-text">Welcome,</span>
            <span className="username">{user?.username}</span>
          </div>
          <button onClick={handleLogout} className="logout-btn">
            🚪 Logout
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="main-content">
        <header className="dashboard-header">
          <h1>MOONBERRY Inventory Management</h1>
          <div className="header-info">
            <span className="current-date">
              {currentTime.toLocaleDateString('en-US', { 
                weekday: 'long', 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric' 
              })}
            </span>
            <span className="current-time">
              {currentTime.toLocaleTimeString('en-US', {
                hour: '2-digit',
                minute: '2-digit',
                second: '2-digit',
                hour12: true
              })}
            </span>
          </div>
        </header>
        
        <div className="dashboard-content">
          {renderContent()}
        </div>
      </div>
    </div>
  );
};

export default Dashboard;